// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockEntropy$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockEntropy";
  readonly sourceName: "contracts/tests/mocks/MockEntropy.sol";
  readonly abi: [{"inputs":[],"name":"requestV2","outputs":[{"internalType":"uint256","name":"requestId","type":"uint256"}],"stateMutability":"pure","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b50607480601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c80637b43155d14602a575b5f5ffd5b600160405190815260200160405180910390f3fea2646970667358221220e47b10c198ffd65d0636ac9a0e5e739fd91c96a519cd594daecf61a902ed710464736f6c634300081c0033";
  readonly deployedBytecode: "0x6080604052348015600e575f5ffd5b50600436106026575f3560e01c80637b43155d14602a575b5f5ffd5b600160405190815260200160405180910390f3fea2646970667358221220e47b10c198ffd65d0636ac9a0e5e739fd91c96a519cd594daecf61a902ed710464736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/tests/mocks/MockEntropy.sol";
  readonly buildInfoId: "solc-0_8_28-df36bada06662e267038712807a90e14f1da6b85";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockEntropy"]: MockEntropy$Type;
    ["contracts/tests/mocks/MockEntropy.sol:MockEntropy"]: MockEntropy$Type;
  }
}